Script updates.
cockroachlabs/cloud-report pull request #122
Opened 2022-02-16 18:12 UTC by miretskiy

Various script updates:
  * When fetching tpcc results, also produce per-run cpu info file across all nodes.
  * Update run tpcc script to be more interactive.
  * Make it possible to specify TPCC_EXTRA_ARGS via environment.
  * Remove ".bak" file nonsense.

2022-02-16 18:16 UTC, srosenberg commented on run_tpcc_experiment.sh
> +#!/opt/homebrew/bin/bash
Do we really need a newer version of bash?

2022-02-16 18:22 UTC, srosenberg commented on cmd/generate.go
> -      if [[ "$prev_line" != *efc* ]] || [[ $(tail -1 "$result_file" | awk '{if(int($3) > 87){print "pass"}}') != "pass" ]];
Thanks for cleaning up `.bak` nonsense :) We'll need to update `analyze` to optionally include "failed" runs. I can do that in my PR [1] after we merge yours.

[1] https://github.com/cockroachlabs/cloud-report/pull/119

2022-02-16 22:43 UTC, ZhouXing19 approved these changes

2022-02-16 22:45 UTC, ZhouXing19 commented on run_tpcc_experiment.sh
> +      mapfile -t scriptPaths < <( find ./report-data/$curdate/aws -name "*.sh" )
I think we can switch back to 
`scriptPaths=($(find ./report-data/$curdate/aws -name "*.sh" |tr '\n' ' '))`, which doesn't require a newer bash

2022-02-17 15:50 UTC, ZhouXing19 requested changes

2022-02-17 15:50 UTC, ZhouXing19 commented on run_tpcc_experiment.sh
> +      echo "Sleeping for 10s"
Looks like it should be changed to "TPCC_EXTRA_ARGS=$extra_arg"

2022-02-23 16:14 UTC, merged